### ISSUE TITLE
LiteLLM - How to call Mode: 'Query Files'

### ISSUE THREAD

**Issue by K-J-VV** [zylon-ai/private-gpt#1799]
I have PrivateGPT running as well as LiteLLM. I'm able to connect LiteLLM to PrivateGPT, but when prompting the AI the responses default as coming through the Mode: "LLM Chat (no context from files)". In my case, the LLM is provided by Ollama. 

Is there some way to have external calls from LiteLLM to PrivateGPT go through the Mode: "Query Files" instead?

Currently I have the api_base set as the url of PrivateGPT: http://10.10.10.10:8080/v1

Is there a setting somewhere in the yaml, or a url subfolder (e.g., "/v1/Query"), or something that can help me achieve this?

Thanks in advance!

**Comment by jaluma** [comment]
One idea would modify PrivateGPT to always use context, looking for related data, instead of make a non-context inference. 
Please check this line: https://github.com/zylon-ai/private-gpt/blob/15f73dbc4873bfcf26b8ef1760fed45824cae312/private_gpt/server/chat/chat_service.py#L107

If you found a solution or there're something to know, please feel free to tell us, many people would be in the same situation.:)
