### ISSUE TITLE
Why is a tokenizer required if running in ollama mode?

### ISSUE THREAD

**Issue by tim-roethig-db** [zylon-ai/private-gpt#1864]
I am using privateGPT in ollama mode and found out that this [parameter](https://github.com/zylon-ai/private-gpt/blob/94ef38cbba8fe5e406eb192efafe774b9aadb564/settings.yaml#L42) is still used [here ](https://github.com/zylon-ai/private-gpt/blob/94ef38cbba8fe5e406eb192efafe774b9aadb564/private_gpt/components/llm/llm_component.py#L26).

Is that correct? I would have expected that with ollama all tokenization happens in ollama itself.

Also it looks like privateGPT still relies somehow on this tokenizer. Because after removing it something tries to pull the gpt3.5 tokenizer from the web [here](https://github.com/zylon-ai/private-gpt/blob/347be643f7929c56382a77c3f45f0867605e0e0a/private_gpt/server/chat/chat_service.py#L96).

**Comment by KansaiTraining** [comment]
I also want to know why is tokenizer needed.
In fact it seems it accesses an external site that needs authentication
I thought the ollama mode was totally local
I removed it and it still run

**Comment by jaluma** [comment]
In order to calculate the exact number of tokens, we need to have the tokenizer downloaded and accessible. Since ollama does not allow to calculate tokens via API, that is the reason.
There have been a lot of problems related to that. We've thought that the best idea is to make it optional, and use the llama-index one if you can't download it, avoiding problems.
