### ISSUE TITLE
Query Multiple Files

### ISSUE THREAD

**Issue by spsach** [zylon-ai/private-gpt#1896]
How can you query multiple files?

**Comment by KansaiTraining** [comment]
Would like to know this too. 
So far I have ingested several and selected "Search files" not query file
The search is limited to 4 (hardcoded actually)

**Comment by jaluma** [comment]
If you ingest multiple files, by default, it will use all ingested data as knowledge (in `QueryMode`). Otherwise, if you need to use only a few ingested files, you can try filtering them using `context_filter` parameter. Currently, this function is not available through the user interface, only through the API.
