### ISSUE TITLE
Dynamic database path

### ISSUE THREAD

**Issue by Alexng2024** [zylon-ai/private-gpt#2018]
### Question

I am thinking is there anyway that allow different users store their own db in different folders?  
in which file the model will check the db folder?  I found the ingest_component allow to modify but where is the one that ask the model to check?

Thanks

**Comment by psychopatz** [comment]
You can edit the default db location in the [settings.yaml](https://github.com/zylon-ai/private-gpt/blob/main/settings.yaml) in this line

```
data:
  local_data_folder: local_data/private_gpt
```

Its kinda hassle tho since you need to restart the app for it to take effect, If you want this kind of flexibility to your App/Website, use LLMware, it supports dynamic db switching but kinda tricky to set up tho
